### ISSUE TITLE
(wrong-type-argument sequencep :null) sample "Async Read API"

### ISSUE THREAD

**Issue by yamatakau08** [mhayashi1120/Emacs-esqlite#6]
I execute the following code with referring sample "Async Read API"

`(esqlite-async-read english_phrase_db "SELECT * FROM headings"
		    (lambda (data) (message "%s" (mapconcat 'identity data ", "))))`

I got the following error.
esqlite issue?
or my sqlite3 database table null data is not good?

`
Debugger entered--Lisp error: (wrong-type-argument sequencep :null)
  mapconcat(identity ("1" "うれしい・楽しい" "0" "スタンダード表現" "0" "わーい!" "Wow!" "Wow! は、喜び、驚き(「わーぁ!」)、賞賛(「すごい」)などを表す。" "Whoopee!" :null :null :null :null "0" "Let's eat out tonight." "今夜は食事にでかけようよ" "Wow! I want to have sushi." "わーい! 私、お寿司がたべたいな") ", ")
  (message "%s" (mapconcat (quote identity) data ", "))
  (lambda (data) (message "%s" (mapconcat (quote identity) data ", ")))(("1" "うれしい・楽しい" "0" "スタンダード表現" "0" "わーい!" "Wow!" "Wow! は、喜び、驚き(「わーぁ!」)、賞賛(「すごい」)などを表す。" "Whoopee!" :null :null :null :null "0" "Let's eat out tonight." "今夜は食事にでかけようよ" "Wow! I want to have sushi." "わーい! 私、お寿司がたべたいな"))
 ...
  esqlite-async-read--filter(#<process Esqlite>
  accept-process-output(#<process Esqlite> 0.20775294303894043)
  esqlite-sleep(#<process Esqlite>)
  esqlite-async-read--maybe-error(#<process Esqlite>)
  esqlite-async-read("~/bin/sqlite3_sample/english_phrase.db" "SELECT * FROM headings" (lambda (data) (message "%s" (mapconcat (quote identity) data ", "))))
  eval((esqlite-async-read english_phrase_db "SELECT * FROM headings" (function (lambda (data) (message "%s" (mapconcat (quote identity) data ", "))))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
`

**Comment by mhayashi1120** [comment]
```
(esqlite-async-read
 english_phrase_db
 "SELECT * FROM headings"
 (lambda (data)
   (unless (eq data :EOF)
     (message "%s" (mapconcat (lambda (x) (if (eq :null x) "" x)) data ", ")))))
```

You need special handling NULL (== :null) value. I have desined the library Three-valued logic (三値論理)
Surely it is difficult to understand, i think.

**Comment by yamatakau08** [comment]
`You need special handling NULL (== :null) value.`

I see.
Thank you for providing code.
It works fine.
